#pragma once



// Master File Table
typedef enum
{
	MFT_ATTRIBUTE_DOLLAR_STANDARD_INFORMATION 		= 0x10,
	MFT_ATTRIBUTE_DOLLAR_ATTRIBUTE_LIST 			= 0x20,
	MFT_ATTRIBUTE_DOLLAR_FILE_NAME					= 0x30,
	MFT_ATTRIBUTE_DOLLAR_OBJECT_ID					= 0x40,
	MFT_ATTRIBUTE_DOLLAR_SECURITY_DESCRIPTOR		= 0x50,
	MFT_ATTRIBUTE_DOLLAR_VOLUME_NAME				= 0x60,
	MFT_ATTRIBUTE_DOLLAR_VOLUME_INFORMATION			= 0x70,
	MFT_ATTRIBUTE_DOLLAR_DATA						= 0x80,	
	MFT_ATTRIBUTE_DOLLAR_INDEX_ROOT					= 0x90,
	MFT_ATTRIBUTE_DOLLAR_INDEX_ALLOCATION			= 0xA0,
	MFT_ATTRIBUTE_DOLLAR_BITMAP						= 0xB0,
	MFT_ATTRIBUTE_DOLLAR_REPARSE_POINT				= 0xC0,
	MFT_ATTRIBUTE_DOLLAR_EA_INFORMATION				= 0xD0,
	MFT_ATTRIBUTE_DOLLAR_EA							= 0xE0,
	MFT_ATTRIBUTE_DOLLAR_LOGGED_UTILITY_STREAM		= 0x100,
	MFT_ATTRIBUTE_DOLLAR_MAX						
}MFT_ATTRIBUTE_TYPE;

